site_name: Ongaku LavaLyrics Docs

site_url: https://lavalyrics.ongaku.mplaty.com/

repo_url: https://github.com/MPlatypus/ongaku-lavalyrics/


theme:
  name: material
  palette:
    scheme: slate
    primary: custom
    accent: custom
  font:
    text: Quicksand
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - search.suggest
    - content.code.copy
  logo: assets/logo.png
  favicon: assets/favicon.png


extra_css:
  - stylesheets/extra.css


plugins:
  - search
  - social:
      cards_layout_options:
        background_color: "#ff6b61"
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          import:
            - https://docs.python.org/3.10/objects.inv
            - https://docs.hikari-py.dev/en/latest/objects.inv
            - https://tanjun.cursed.solutions/objects.inv
            - https://arc.hypergonial.com/objects.inv
            - https://ongaku.mplaty.com/objects.inv
          options:
            heading_level: 3
            annotations_path: source
            docstring_section_style: spacy
            docstring_style: numpy
            inherited_members: true
            merge_init_into_class: true
            separate_signature: true
            show_signature_annotations: true
            show_source: false
            show_submodules: false
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            members_order: source
            extensions:
                - griffe_inherited_docstrings


markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


copyright: Copyright &copy; 2024-present MPlaty

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MPlatypus/hikari-ongaku
      name: Ongaku LavaLyrics Github


nav:
  - home: index.md
  - Getting Started:
    - gs/index.md
  - API Reference:
    - api/index.md
    - ABC: api/abc.md
    - Extension: api/extension.md
  - Changelog: changelog.md


watch:
  - docs
  - ongaku
